# Generated by Django 5.2.5 on 2025-11-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sucursales.sucursal'),
        ),
    ]
