# Generated by Django 5.2.5 on 2025-11-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='canal',
            field=models.CharField(blank=True, choices=[('POS', 'Punto de Venta'), ('WEB', 'Tienda en Línea'), ('OTRO', 'Otro')], default='POS', max_length=10, null=True),
        ),
    ]
