# Generated by Django 5.2.5 on 2025-11-09 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('max_usuarios', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_productos', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ventas_mensuales', models.PositiveIntegerField(blank=True, null=True)),
                ('almacenamiento_gb', models.PositiveIntegerField(default=1)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('permite_reportes_ia', models.BooleanField(default=False)),
                ('permite_exportar_excel', models.BooleanField(default=False)),
                ('permite_notificaciones_push', models.BooleanField(default=False)),
                ('soporte_prioritario', models.BooleanField(default=False)),
                ('esta_activo', models.BooleanField(default=True)),
                ('prediccion_ventas', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.plan')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
            },
        ),
    ]
