# Generated by Django 5.2.5 on 2025-11-11 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('esta_activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa')),
            ],
            options={
                'db_table': 'report_definition',
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('formato', models.CharField(default='csv', max_length=10)),
                ('estado', models.CharField(default='PENDING', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reports.reportdefinition')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_run',
            },
        ),
    ]
