# Generated by Django 5.2.5 on 2025-11-09 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        ('sucursales', '0001_initial'),
        ('tenants', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envio',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.direccion'),
        ),
        migrations.AddField(
            model_name='envio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='envio',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
