# Generated by Django 5.2.5 on 2025-11-09 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
                'ordering': ['-fecha'],
            },
        ),
    ]
