# Generated by Django 5.2.5 on 2025-11-09 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.CharField(blank=True, max_length=100, null=True)),
                ('velocidades', models.CharField(blank=True, max_length=100, null=True)),
                ('voltaje', models.CharField(blank=True, max_length=100, null=True)),
                ('aire_frio', models.CharField(blank=True, max_length=100, null=True)),
                ('tecnologias', models.CharField(blank=True, max_length=255, null=True)),
                ('largo_cable', models.CharField(blank=True, max_length=100, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ficha Técnica (Detalle)',
                'verbose_name_plural': 'Fichas Técnicas (Detalles)',
                'db_table': 'detalle_producto',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='productos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'db_table': 'imagen_producto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='El párrafo de marketing (Información Adicional)', null=True)),
                ('sku', models.CharField(blank=True, help_text='Código único de producto (SKU) para gestión e inventario', max_length=100, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto (SKU)',
                'verbose_name_plural': 'Productos (SKUs)',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subcategoría (Nivel 2)',
                'verbose_name_plural': 'Subcategorías (Nivel 2)',
                'db_table': 'subcategoria',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('esta_activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanias', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campania',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Categoría (Nivel 1)',
                'verbose_name_plural': 'Categorías (Nivel 1)',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO', 'Monto Fijo')], max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('campania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos', to='products.campania')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'db_table': 'descuento',
            },
        ),
    ]
